### ISSUE TITLE
SignonHandler Example Implimentation?

### ISSUE THREAD

**Issue by 3000geminihunter** [i8beef/SAML2#11]
Not sure if this can be labelled an issue. I am new to .NET. I do know SAML2.0 specs well from a research perspective. I am trying to implement a SAML Client for testing and consuming a SAML response (coming from Postman (www.getpostman.com/) at the moment). I've installed the NuGet packages to my project. Wondering if there is any example of how to write the handlers (login.ashx, logout.ashx, metadata.ashx)? For the moment, an example implementation of login.ashx would be very helpful.  Thanks.

**Comment by i8beef** [comment]
Those handlers are provided by the library. The first code block in the Wiki on the first page shows you how to turn them on and map them to those endpoints. They handle parsing and validating SAML messages that come through. Once the validation has occurred, it will execute Actions where appropriate, which you can define (each action has a login and logout method which are executed according to what action was just validated). See the section in the Wiki about custom Actions. Typical usage would leave the SamlPrincipal and Redirect actions, but replace the FormsAuthentication action with your own implementation. That would just be a class in your own app that inherits from Action and implements those two methods, and it would authorize your app session with the identity that the SAML handshake presented.

**Comment by 3000geminihunter** [comment]
Thank you.
