### ISSUE TITLE
Is there example code available?

### ISSUE THREAD

**Issue by hugodevreugd** [i8beef/SAML2#12]
Maybe I missed it, but is there sample code for login.ashx, etc. So the code of the service provider side of the SAML interactions. (Mainly for single sign-on only.)
I'm a bit stuck here.

Thanks in advance.

**Comment by i8beef** [comment]
No, you don't write those handlers, they are provided by the framework. What you are probably looking for is Actions, which define what actions to execute after a successful login / logout handshake. See the Wiki: https://github.com/i8beef/SAML2/wiki/Custom-Authentication-Process
