### ISSUE TITLE
Using of not initialized logging provider instance

### ISSUE THREAD

**Issue by sababa** [i8beef/SAML2#16]
Hello,

Thank you for doing great job with the library.

There is a small issue I found in the code:
In [IdentityProviderCollection.cs line #357](https://github.com/i8beef/SAML2/blob/master/src/SAML2/Config/IdentityProviderCollection.cs#L357) instance of `LoggerProvider` might be not initialized. It throws null reference exception instead of reporting of idp metadata problem. That happens because `IdentityProviderCollection.Refresh()` method call in `Saml2Config.GetConfig()` occurs before `LoggerProvider` instance is constructed.

In order to reproduce the issue, create file with malformed idp metadata and point browser to login endpoint.

**Comment by i8beef** [comment]
Hmm that might be tricky. You're right there's a catch-22 here as this could get executed during initialization... the logging was added more around the REFRESH logic of the library, but I'd actually expect it to fail on the second call to GetConfig() within the singleton creation method of the LogProvider. Can you send the stack trace you are getting?

**Comment by sababa** [comment]
I guess it happens because you're trying to get logger during Saml20SignonHandler instantiation at AbstractEndpointHandler.cs line #17. Then you're calling to GetConfig() from LoggerProvider constructor which calls to Refresh() which eventually tries to log something.
Final stack trace is completely irrelevant but attached picture with debug stop at  IdentityProviderCollection.cs line #357 could be useful.
![saml2-exception](https://cloud.githubusercontent.com/assets/1135733/25855747/130c998c-34a2-11e7-90c2-b05523daf4f5.JPG)

**Comment by i8beef** [comment]
Yes I know where and why it happens, I'm just curious what the actual error exception is you are getting. Where this is happening I'd expect an infinite loop from this. Easiest fix here is probably to just drop the try catch and assume only valid metadata files here, but I'm unsure if that's what I want to do yet. I could silently swallow it too, but that doesn't sound good either as you'd never know you had an IDP metadata problem.

It's a bug for sure, and one I'd like to do something different about, but it's definitely an edge case. Seems as long as you can parse the IDP metadata properly you wouldn't hit this, but this logging would only be effective on refreshes post initial configuration. Guess I might try grabbing the specific logging configuration element instead of trying to grab the whole configuration first...

Ill have to consider the right course here, thanks for the report.

**Comment by sababa** [comment]
Last exception I've got is as following:

Source Error:
```
Line 616:
Line 617:            // Determine which endpoint to use from the configuration file or the endpoint metadata.
Line 618:            var destination = DetermineEndpointConfiguration(BindingType.Redirect, identityProvider.Endpoints.SignOnEndpoint, identityProvider.Metadata.SSOEndpoints);
Line 619:            request.Destination = destination.Url;
Line 620:
```
Source File: `...\SAML2\src\SAML2\Protocol\Saml20SignonHandler.cs`    Line: 618 

Stack Trace: 
```
[NullReferenceException: Object reference not set to an instance of an object.]
   SAML2.Protocol.Saml20SignonHandler.TransferClient(IdentityProviderElement identityProvider, Saml20AuthnRequest request, HttpContext context) in c:\Dev\tests\SAML2Test\SAML2\src\SAML2\Protocol\Saml20SignonHandler.cs:618
   SAML2.Protocol.Saml20SignonHandler.SendRequest(HttpContext context) in c:\Dev\tests\SAML2Test\SAML2\src\SAML2\Protocol\Saml20SignonHandler.cs:603
   SAML2.Protocol.Saml20SignonHandler.Handle(HttpContext context) in c:\Dev\tests\SAML2Test\SAML2\src\SAML2\Protocol\Saml20SignonHandler.cs:172
   SAML2.Protocol.Saml20AbstractEndpointHandler.ProcessRequest(HttpContext context) in c:\Dev\tests\SAML2Test\SAML2\src\SAML2\Protocol\Saml20AbstractEndpointHandler.cs:81
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +188
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69

```
I don't remember exactly but I guess previous time I've got exception in another place.

You're right it's not good idea to swallow this exception. I had to clone your repository and start debugging in order to find what's wrong. What would user do if there is no exception at all but idp metadata is malformed? 
Grabbing specific logging configuration in LoggingProvider constructor sounds good. You might want to introduce separate method in Saml20Config for logger. Also you might throw specific exception from LoggerFor method if logger instance is null.

You're welcome and thanks again for good job.

**Comment by i8beef** [comment]
I have created a branch with an updated configuration / logging situation. If you get a chance, try it out and let me know if you get the same issue.

**Comment by i8beef** [comment]
Merged to master. Awaiting next release.
