### ISSUE TITLE
[Support] Assertion Checks

### ISSUE THREAD

**Issue by TheDarkTrumpet** [i8beef/SAML2#18]
Hello,

I got most stuff working, and when I have the skip of assertion enabled, it does correctly route to my controller. So far so good, but the certificate is a bit confusing.

I'm using TestShib, a Shibboleth provider, for authentication against university systems (which use Shibboleth).  I wasn't able to load their XML directly, so I used https://www.samltool.com/sp_metadata.php to generate a new one based off the information in their current file.

TestShib's metadata is located at: https://www.testshib.org/metadata/testshib-providers.xml

If I turn on omitAssertionSignatureCheck, everything does work - but I don't think this is the most secure solution.

My XML file that I currently have is:
https://gist.github.com/TheDarkTrumpet/cb70f7d66f1a069e3d8218fff0664ab0

The failure seems to be around the area for assertion checks (HandleAssertion in https://github.com/i8beef/SAML2/blob/master/src/SAML2/Protocol/Saml20SignonHandler.cs), which seems to be a problem validating the signature.

The signature that the XML (X509Certificate) provides is:
`MIIDAzCCAeugAwIBAgIVAPX0G6LuoXnKS0Muei006mVSBXbvMA0GCSqGSIb3DQEB CwUAMBsxGTAXBgNVBAMMEGlkcC50ZXN0c2hpYi5vcmcwHhcNMTYwODIzMjEyMDU0 WhcNMzYwODIzMjEyMDU0WjAbMRkwFwYDVQQDDBBpZHAudGVzdHNoaWIub3JnMIIB IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAg9C4J2DiRTEhJAWzPt1S3ryh m3M2P3hPpwJwvt2q948vdTUxhhvNMuc3M3S4WNh6JYBs53R+YmjqJAII4ShMGNEm lGnSVfHorex7IxikpuDPKV3SNf28mCAZbQrX+hWA+ann/uifVzqXktOjs6DdzdBn xoVhniXgC8WCJwKcx6JO/hHsH1rG/0DSDeZFpTTcZHj4S9MlLNUtt5JxRzV/MmmB 3ObaX0CMqsSWUOQeE4nylSlp5RWHCnx70cs9kwz5WrflnbnzCeHU2sdbNotBEeTH ot6a2cj/pXlRJIgPsrL/4VSicPZcGYMJMPoLTJ8mdy6mpR6nbCmP7dVbCIm/DQID AQABoz4wPDAdBgNVHQ4EFgQUUfaDa2mPi24x09yWp1OFXmZ2GPswGwYDVR0RBBQw EoIQaWRwLnRlc3RzaGliLm9yZzANBgkqhkiG9w0BAQsFAAOCAQEASKKgqTxhqBzR OZ1eVy++si+eTTUQZU4+8UywSKLia2RattaAPMAcXUjO+3cYOQXLVASdlJtt+8QP dRkfp8SiJemHPXC8BES83pogJPYEGJsKo19l4XFJHPnPy+Dsn3mlJyOfAa8RyWBS 80u5lrvAcr2TJXt9fXgkYs7BOCigxtZoR8flceGRlAZ4p5FPPxQR6NDYb645jtOT MVr3zgfjP6Wh2dt+2p04LG7ENJn8/gEwtXVuXCsPoSCDx9Y0QmyXTJNdV1aB0AhO RkWPlFYwp+zOyOIR+3m1+pqWFpn0eT/HrxpdKa74FA3R2kq4R7dXe4G0kUgXTdqX MLRKhDgdmA==` 

This matches my certificate.  I tried all of it on one line, and split on multiple lines like it is in the XML. No go on each.  With logging enabled, I'm getting this part of it:

`09.10.2017 13:43:04.5158 [13] DEBUG SAML2.Protocol.AbstractEndpointHandler - Processing assertion: <saml2:Assertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:xs="http:
//www.w3.org/2001/XMLSchema" ID="_39d1718284332c253c6cc557ada1dbc3" IssueInstant="2017-10-09T18:43:04.117Z" Version="2.0"><saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-form
at:entity">https://idp.testshib.org/idp/shibboleth</saml2:Issuer><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http:
//www.w3.org/2001/10/xml-exc-c14n#"></ds:CanonicalizationMethod><ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"></ds:SignatureMethod><ds:Reference UR
I="#_39d1718284332c253c6cc557ada1dbc3"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"></ds:Transform><ds:Transform Algorithm="http://ww
w.w3.org/2001/10/xml-exc-c14n#"><ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="xs"></ec:InclusiveNamespaces></ds:Transform></ds:Transforms><ds:
DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"></ds:DigestMethod><ds:DigestValue>tTh++eSRpTaLYfEdzabPQ3lGP+Bpr+mEzPG2ut5FbCw=</ds:DigestValue></ds:Reference></ds:Sig
nedInfo><ds:SignatureValue>DkA7dbGZyWFN1VMCEqFYRrAud8gPR88X49VON1XYioZEk6nzW9V4sCLCGt9/SV0S5ezXzCfzH5SHXz8HP55ftxK/KZ76F7D1534qurMKOfgfjZOQNyMLQDbBAMcwaGT5mY9YLZ6dObfYVONlAmfmCDbItsMY
PtgxjRs3i3fZOK2i1aFwu+ergGg1bk77gCmNB7+92UA2bghygvxvlz15BwBLgmPO2ykodILOaqApkJUCPbIRqGA6XRjDnjClHS9Zi6DTAijKFnMNArpLOH+7bbccJSMa5nWkpohJP9Ee4rxDYajmQGZl91uVazetyBbOI9cmebBsBlWW/CaEwGx
z7Q==</ds:SignatureValue><ds:KeyInfo><ds:X509Data><ds:X509Certificate>MIIDAzCCAeugAwIBAgIVAPX0G6LuoXnKS0Muei006mVSBXbvMA0GCSqGSIb3DQEBCwUAMBsxGTAX
BgNVBAMMEGlkcC50ZXN0c2hpYi5vcmcwHhcNMTYwODIzMjEyMDU0WhcNMzYwODIzMjEyMDU0WjAb
MRkwFwYDVQQDDBBpZHAudGVzdHNoaWIub3JnMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
AQEAg9C4J2DiRTEhJAWzPt1S3ryhm3M2P3hPpwJwvt2q948vdTUxhhvNMuc3M3S4WNh6JYBs53R+
YmjqJAII4ShMGNEmlGnSVfHorex7IxikpuDPKV3SNf28mCAZbQrX+hWA+ann/uifVzqXktOjs6Dd
zdBnxoVhniXgC8WCJwKcx6JO/hHsH1rG/0DSDeZFpTTcZHj4S9MlLNUtt5JxRzV/MmmB3ObaX0CM
qsSWUOQeE4nylSlp5RWHCnx70cs9kwz5WrflnbnzCeHU2sdbNotBEeTHot6a2cj/pXlRJIgPsrL/
4VSicPZcGYMJMPoLTJ8mdy6mpR6nbCmP7dVbCIm/DQIDAQABoz4wPDAdBgNVHQ4EFgQUUfaDa2mP
i24x09yWp1OFXmZ2GPswGwYDVR0RBBQwEoIQaWRwLnRlc3RzaGliLm9yZzANBgkqhkiG9w0BAQsF
AAOCAQEASKKgqTxhqBzROZ1eVy++si+eTTUQZU4+8UywSKLia2RattaAPMAcXUjO+3cYOQXLVASd
lJtt+8QPdRkfp8SiJemHPXC8BES83pogJPYEGJsKo19l4XFJHPnPy+Dsn3mlJyOfAa8RyWBS80u5
lrvAcr2TJXt9fXgkYs7BOCigxtZoR8flceGRlAZ4p5FPPxQR6NDYb645jtOTMVr3zgfjP6Wh2dt+
2p04LG7ENJn8/gEwtXVuXCsPoSCDx9Y0QmyXTJNdV1aB0AhORkWPlFYwp+zOyOIR+3m1+pqWFpn0
eT/HrxpdKa74FA3R2kq4R7dXe4G0kUgXTdqXMLRKhDgdmA==</ds:X509Certificate></ds:X509Data></ds:KeyInfo></ds:Signature><saml2:Subject><saml2:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" NameQualifier="https://idp.testshib.org/idp/shibboleth" SPNameQualifier="urn:SPName">_f851f35ff8a2b154fc88bf7db5d43835</saml2:NameID><saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer"><saml2:SubjectConfirmationData Address="108.160.236.43`

The signature value (<ds:SignatureValue>), I thought, was interesting.  I'm not really sure what that's even used for.  I'm not the most familiar with SAML yet.  I'm about to dip into Linqpad and try to make the same general signature check that you're making and see if I can figure out what's going on from that end.  But, if SignatureValue is important for something, I wouldn't mind knowing more about this.

Thanks for your help on this.  I found a few more documentation areas that, once I get this fully working, I hope to send to you for updates.  I am also developing this project in an isolated manner, for the primary purpose of just testing SAML.  Hopefully this could be of use to others trying to figure out how to use SAML.

**Comment by TheDarkTrumpet** [comment]
This is kinda odd, but I ran it again, and copied the cert from the logs back into the config.  The logs had:

`MIIC7DCCAdSgAwIBAgIQcBqwW0Hvb4JFYaFZSZLhoDANBgkqhkiG9w0BAQsFADAUMRIwEAYDVQQD
Ewlsb2NhbGhvc3QwHhcNMTcwODE4MjAzOTIzWhcNMjIwODE4MDAwMDAwWjAUMRIwEAYDVQQDEwls
b2NhbGhvc3QwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDSQLJdU44SFqFDtZxH2OoU
YKG0Xd/b/sINlPyH+NRQSjXAmo5GLVPoNeJVzBRV9WwaSdOa9z6Vdw4QxwciSOGf/sA7fxx+QXbb
MxQpBCan2o8ZGHB+TwokxOGTOHKZ/3nIO+N8Nap74a7eUkMtK/dr8iw+t5cUzbJmo0w+yaeUbeRs
t8zPVdffI5j2KoXddYX1gMN0CI1nwB8z1ny9IHwJvjR0jaAXEnf917Bnz1vBiKIdv6yjhQOW0lG0
FVtFaVCIHj0R6EOpx+nEB/ltTBh9JG/+HvYGBaGn46YGfSa4lz+03YhwXQStKqLtpY3I+hXsvmV2
razMof9EDhRLxDzRAgMBAAGjOjA4MAsGA1UdDwQEAwIEsDATBgNVHSUEDDAKBggrBgEFBQcDATAU
BgNVHREEDTALgglsb2NhbGhvc3QwDQYJKoZIhvcNAQELBQADggEBAAPsrmz3nhiQ+F4SOtJgY6hW
0az/rpj53T90IZmjI92yR2CAG4NgVrgA9ZajKpokUv1ZbUlQ5dJTG5KgXB6yTl6ML8dDo0hiNQ94
sbzLPAHba9FoIgWawlVB+6xbX5/x5DJK00JMu6KqY8GiDyqHxqXDf2BQdrn1OgE3jxo4LAgDeJzF
mqhBIvbpLMvH/yw2QUx89DYFXlR1PJoM28upkkOydkP6b32AJHBNTk0RMNNRVIqds6BUTLvLOlX6
pMUEaBPdij5LNtT6t53XX/0mOpyqy7SZ//xvbTRcueWOoAjnwaQjdPeDASzyPe12OPE93agG7ilL
xHEdjwcKZSLbKPY=`

For the cert

**Comment by i8beef** [comment]
Signature algorithms are designed to allow two parties (IDP and SP in this case) to ensure that the message hasn't been tampered with en-route. Since you are inherently modifying that message by generating a new metadata document manually, the old signature won't work, and a new one would need to be generated to match the new document. That tool seems like it might have the capability to do that, if you provide the Shiboleth cert and private key to it... but I can't recommend you do that for security reasons. Anytime anything says "just paste your private key here" should be a massive decision (really, one that ends with the word "No") that I suggest you talk over with your IT security people first.

That said, you might be able to generate this WITHOUT the signature and use it as is. If the message isn't signed, I think the signature check is skipped on the metadata documents.

As a third piece, I'd be mildly interested in what importing that original metadata document failed on to see if I could help guide you to making that work.

**Comment by TheDarkTrumpet** [comment]
Hey,

Thanks for responding and the description that helped.  So my hunch about taking the original and pruning it to what I explicitly need won't work either for the same reason.

The log message doesn't really tell me much, unfortunately.  It shows it as:

`09.10.2017 19:30:55.3793 [12] ERROR SAML2.Config.IdentityProviderCollectionSystem.NullReferenceException: <83>I<83>u<83>W<83>F<83>N<83>g<8E>Q<8F>Ƃ<AA><83>I<83>u<83>W<83>F<83>N<83>g 
<83>C<83><93><83>X<83>^<83><93><83>X<82>ɐݒ肳<82><EA><82>Ă<A2><82>܂<B9><82><F1><81>B
   <8F>ꏊ SAML2.Config.IdentityProviderCollection.ParseFile(String file)
 - Problem parsing metadata file
09.10.2017 19:30:55.4014 [12] ERROR SAML2.Config.IdentityProviderCollectionSystem.NotImplementedException: <83><81><83>\<83>b<83>h<82>܂<BD><82>͑<80><8D><EC><82>͎<C0><91><95><82><B3><82><EA><82>Ă<A2><82>܂<B9><82><F1><81>B
   <8F>ꏊ SAML2.Config.IdentityProviderCollection.ParseFile(String file)
 - Problem parsing metadata file`

I'm going to work on this some tonight, I'll see if I can get the symbol debugging working, and see if I can track down what's going on.

**Comment by TheDarkTrumpet** [comment]
Alright, I think I may have tracked down the issue.

It looks like it's in IdentityProviderCollection, ParseFile (https://github.com/i8beef/SAML2/blob/c07b7a475779ddb24daac1ffb15400b367da2d34/src/SAML2/Config/IdentityProviderCollection.cs)

If I'm understanding this correctly, it's looking for a node with the namespace of "urn:oasis:names:tc:SAML:2.0:metadata".  This does appear in the original metadata file, but under the root node "EntitiesDescriptor". It appears that because it's not under EntityDescriptor (singular), that it's not finding it.

I started using Linqpad to try and trace this down more specifically, but since a lot of methods are private, that's hard to do.  I think I'll try checking out the main project and tests, and add this to tests and write a test case for it. At least then I should be able to step through the code easier by using the test.

**Comment by i8beef** [comment]
No, its finding it, but looks like the project doesn't support multiple EntityDescriptors in a single file. You might legitimately try modifying the metadata doc to remove the second entity, and just strip off the signature. That trick wont work for messages and such, but for metadata that might be your easiest track. Changing metadata parsing here might be easy, or could have farther reaching consequences... Id have to dig through and make sure everything is OK with multiple.

**Comment by i8beef** [comment]
This could probably be done by refactoring the IDP metadata file parsing around the location you linked to. It just assumes that the file contains only one IDP descriptor, but that could be changed to support multiple. I'll take a look this weekend and see if I can get that going for you.

**Comment by i8beef** [comment]
I had a few minutes so I played with this. I haven't tested it yet, which I will when I get time so I can add some unit tests around trying this with your example IDP metadata file, but I think this should work. Possible that I'll need to do some more work on it though, as I'm unsure if I need to copy of IDP metadata node namespaces around to make things correct... You're welcome to pull, compile and try it if you want in the mean time.

**Comment by i8beef** [comment]
Merged to master, awaiting testing and release.

**Comment by TheDarkTrumpet** [comment]
Thanks for working on this.  I had to switch to another task late last week, and am wrapping that up now.  I'll definitely try this, and will get back to you by tomorrow afternoon (my time - CST).  Thanks again for working on this.

**Comment by i8beef** [comment]
Note, this is still in the master branch. I didn't put a release together yet, so you'll need to pull down master and build and copy to test. If it works for you on at least that, then I can clear it to be in the next set of patches that I'm putting together here.

**Comment by TheDarkTrumpet** [comment]
I worked with this some tonight, and found a few things.  First, I tried multiple types of Ids for the metadata reference.  One ID was:

urn:mace:shibboleth:testshib:two

The other was:

https://idp.testshib.org/idp/shibboleth

The first is for the EntitiesDescriptor (main declaration), the second was for the EntityDescriptor.  Neither would show the loaded file at all.  Not even the label.

I uploaded the project to a private repository and sent you a link, if that's at all helpful.  Right now it has your library as a submodule.  The branch is under SAMLNewTest.

I'm going to work at getting the logging back in.  I found the Logging library didn't work with the newest version of Log4Net, apparently some interfaces changed.  I'm looking into that now.

**Comment by i8beef** [comment]
You mean for this?

`<identityProviders metadata="METADATA">`

If so, that is supposed to be a filesystem directory where the app scan for metadata files.

**Comment by TheDarkTrumpet** [comment]
Hey,

I already have that line in, and it reads the uiowa/unc ones just fine.  It doesn't read the pure version of the metadata from TestShib.org.

So in other words, I took my master branch, which had all 3 working then branched from that.  I then replaced the testshib one with the pure version from testshib.org.  I then tried two entity ids, one being the urn:... and the other being the https://.  The actual link, on the main login page (far left button on the home page) wouldn't even list this node's information.  UNC and Uiowa were still listed, but the testshib one was no longer listed.  Usually if the metadata can't be loaded, the friendly name will show with a line struck through it.  

I'll simulate the issue in screenshots and try to post them here.

**Comment by TheDarkTrumpet** [comment]
Alright, I got a few screenshots that may help explain the issue better.

https://i.imgur.com/pXRgxSh.png

The first image is how it works in my master branch, which lists 3 identity providers.  This works, and is kinda my standard right now.  The second image is if I modify the entry point of the idp.testshib.org.xml file, this correctly picks them up - this is also in my master branch.  The third image is it reading both the unc/uiowa metadata files, but no longer reads testshib.org.  This is with trying the two entry points I listed above.

**Comment by i8beef** [comment]
Looking at your metadata document for Shib, entity ID on the IDP configuration definition should definitely be "https://idp.testshib.org/idp/shibboleth" (The one on the EntityDescriptor in the file). 

The reason its falling out of the list of IDPs is because I just made a change that will remove any IDPs that have invalid metadata. I would probably drop a break point into IdentityProviderCollection.cs in the refresh method around this, and see what you are getting back from the metadata parsing. Something isn't parsing right,

**Comment by TheDarkTrumpet** [comment]
Thanks for the feedback on that.  I haven't had much of a chance to look at it today since we're also deploying an application.  I hope to mess with this some more tomorrow or Friday.  I'll post here when I have more information.

I also uploaded a new metadata file, to our test idp in the METADATA.bak folder.  I had to make some changes to make that work, so I'll see if I can figure out why that's happening too and post more detail about that here.  The tl;dr is the lines:
`  <NameIDFormat>urn:mace:shibboleth:1.0:nameIdentifier</NameIDFormat>
  <NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:transient</NameIDFormat>` 
may have caused the bindings to not be found.  I was able to get that working removing these lines, as well as the unsupported protocols (e.g. urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST-SimpleSign).

I should have more information soon about both of these.  Thanks again for your help through all this, and the quick reaction/fixes for all this.  I hope to open another issue about some of the documentation issues.  Around that same time, I hope to make my test application "public" and write some documentation about the things I ran into and how I solved them.

**Comment by i8beef** [comment]
The NameIdFormat I don't think should cause an issue. I'd expect it to throw on the urn:mace:shibboleth:1.0:profiles:AuthnRequest SSO binding, as that's not a binding that is supported. Looking at the spec, I'm not sure they specify an approach in this case... for obvious reasons, as it is basically outside of the supported SAML specification. It might be kosher to simply ignore these endpoint definitions, as this library will never attempt to use them... That would require changing the metadata-to-internal-idp-endpoint translation in Saml20MetadataDocument in the ExtractEndpoints method... basically changing the default in those switches to just drop the endpoint definitions it can't handle...

Let me know what you find. I'd be willing to make the above changes if we test it out in your project first.

**Comment by i8beef** [comment]
Closing as stale.
