### ISSUE TITLE
[Support] Debugging 'Assertion signature is invalid'

### ISSUE THREAD

**Issue by johnmasson** [i8beef/SAML2#34]
I'm in the process of integrating this component into an existing web app (using the latest Nuget package), and testing using StubIDP (https://stubidp.sustainsys.com/). Everything works perfectly as long as I have omitAssertionSignatureCheck="true" on the IDP configuration element. But without this, there doesn't seem to be anything I can do to get signature checks working: all login requests fail with 'Assertion signature is invalid'. I have tried using the 'SelfIssuedCertificateSpecification' in the IDP <certificateValidations> element, and I've tried importing StubIDP's cert into my trusted certs. I haven't tampered with StubIDP's metadata or certificates in any way, nor am I modifying the assertion at all or using any custom login handlers (the default forms auth handler works fine for this app). 

Is there any way I can get more information on why this is failing? I have the logging component installed and configured, but the logs seem to indicate that everything is fine up to the point where the 'Assertion signature is invalid' exception is logged, and processing fails.

Thanks for your work on this component, and I appreciate any help you can give me.

**Comment by i8beef** [comment]
```<SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>```

Looks like they are wanting to do SHA256 signing. This library doesn't support that. See: https://github.com/i8beef/SAML2/issues/20

I am open to pull requests for this if you want to take on modifying it to support this.

**Comment by i8beef** [comment]
Closing as duplicate to #20.
