### ISSUE TITLE
Does this support Azure AD Metadata?

### ISSUE THREAD

**Issue by nreddipalle** [i8beef/SAML2#37]
I have SAML metadata which is SHA256 signed.. Wondering whether this works with Azure AD Metadata or not..
https://docs.microsoft.com/en-us/azure/active-directory/develop/azure-ad-federation-metadata

**Comment by i8beef** [comment]
No, SHA256 support is an open issue.

**Comment by nreddipalle** [comment]
So Just to confirm, a SHA256 IDP metadata is not supported yet. Am I Correct? I am just seeing an error "Invalid File Signature" when trying to configure this metadata and run the app.. and on debugging noticing that XmlSignatureUtils.CheckSignature(doc) method is returning false..

Also I do want to confirm after seeing this https://github.com/i8beef/SAML2/blob/8dfd86989c3a4c7c95e5e0baa850e3f9c7eb532b/src/SAML2/Utils/XmlSignatureUtils.cs#L31 that SHA256 is still supported or not...

Thanks in advance for your response @i8beef .

**Comment by i8beef** [comment]
No, SHA256 signing support is not supported. The original spec didn't allow for any other signing methods at the time. 

See https://github.com/i8beef/SAML2/issues/20

**Comment by i8beef** [comment]
Closed as duplicate
