### ISSUE TITLE
No Identity Providers To Choose From

### ISSUE THREAD

**Issue by Axemasta** [i8beef/SAML2#40]
I managed to get somewhere with this library, I've configured everything up to the identity providers. Now when I browser to `MyApp/Login.ashx` I get the following page:

![my app with no providers](https://user-images.githubusercontent.com/33064621/73277356-f4479380-41e1-11ea-9d6a-04559c6052c3.png)

Unfortnately there is nothing there, the page source shows very little too!
```
<div id="mainPanel">
	<div id="headerPanel">
		Choose Identity Provider
	</div><div id="bodyPanel">
		Please choose the identity provider of your choice from the list below:<br/><br/>
	</div><div id="footerPanel">

	</div>
</div>
```

There is nothing else there unfortunately. 

How is this page configured, I would want to jazz it up for the users of the app..

**Comment by i8beef** [comment]
It isn't configurable. It should only show up when you have multiple IDPs configured or don't have a default sign on endpoint defined i nthe IDP metadata.

**Comment by i8beef** [comment]
I lied. There is a way to specify a CUSTOM IDP selection page location: https://github.com/i8beef/SAML2/wiki/IdentityProviders-Element

So you CAN point to a page you own for customizing this, but I honestly have never seen it used so if you need to do that, you'd have to work up your own implementation.

I think its more likely though, given what you see, that your IDP metadata isn't being loaded at all.
