### ISSUE TITLE
IConfiguration Provider

### ISSUE THREAD

**Issue by denisburlacu** [i8beef/SAML2#45]
Right now we can have just a singleton instance of configuration.
Can we add a configuration provider for this to allow to have multiple configs across one application?
i can implement this and open a PR, but want some opinions if this make sense (based on interface and a external implementation of Configuration Provider, in case if not exist then fallback to existing logic)

**Comment by denisburlacu** [comment]
@i8beef ^^

**Comment by i8beef** [comment]
Can you explain your use case and I can tell you if I think it make sense? Im skeptical right now because everything here is tied to a single application, which should by definition I think only have one configuration.

**Comment by denisburlacu** [comment]
I have an application with multi-tenant architecture, and for each tenant, I need different SAML Configuration.
the idea is in "Saml2Config.Current" before null check and "InitFromConfigFile" we can check if in current AppDomain we have any class that implements a specific interface "ISamlConfigurationProvider" (via reflection and potentially saving a flag if we have a custom implementation of this due to performance reason, or potentially storing this ConfigurationProvider in a property). and in my project, I will have an implementation for this interface where i will return SamlConfiguration based on Current Http Request

**Comment by i8beef** [comment]
I think you'd really have to try it and find the places it breaks... it MIGHT work, though Im unsure if it's gonna cover common domain cookie situations, and this might mess up the state storage parts / leak them between the tenants... you could probably write a new state provider though that established a separation between them, so you don't have the possibility of it trying to use a token from another tenant / validate against an AuthnRequest from another tenant, etc.

I'd also be concerned about your SP signing certificates basically being accessible between tenants. Be real careful there with your security.

Like i said, it might work, but you might find it hard to establish good boundaries between tenants...

**Comment by denisburlacu** [comment]
in my case, each tenant have their own domain, just tried to this via a small snippet and looks like work across multiple tenants with different configs, the only thing will be great to have the ability to do this from Saml project to be always up to date, also potentially in future we can have different SamlConfig providers where who will use this package will take about providers ( for example:
1. from Web.config how is not to be always a default fallback
2. from DB (via a custom implementation of the interface in my project)
3. with multi-tenancy how in my case (via a custom implementation of the interface in my project).

**Comment by i8beef** [comment]
My concern is that this is an AUTH library which means security is job number one here. Multi-tenancy opens a whole can of worms in terms of possible security vulnerabilities. I think if that's your need, you might want to look elsewhere, or fork altogether. I'm not sure any level of testing is going to make me comfortable merging that here, as the risk factors are way too high to introduce vulnerabilites.

I.e., this seems out of scope.
