### ISSUE TITLE
Allow for code based configuration

### ISSUE THREAD

**Issue by i8beef** [i8beef/SAML2#5]
It would be nice to allow for code based configuration, instead of requiring a web.config / app.config based configuration scheme, especially for further unit testing, etc.

**Comment by i8beef** [comment]
Closed out by next release

**Comment by heiny** [comment]
@i8beef - Hi, is this feature implemented?  Looking to utilize your library in a project but we require multi-tenancy support.  In other words, there won't be a single SSO configuration (web.config), it would be configured/saved in a database per customer, so we need the ability to dynamically configure programmatically once the customer is identified via host headers/DNS/textbox on login, etc.

**Comment by i8beef** [comment]
Multitenancy is a different thing that is not supported, and is likely beyond the scope of this library. This simply allows for someone to initialize the global Saml2Config via EITHER reading a web.config section, OR by programmatically configuring it in an application_start, or as part of an OWIN pipeline or something.

Sorry!

**Comment by RZeni** [comment]
@i8beef Can you add some documentation for the config in application_start?

**Comment by i8beef** [comment]
The internal configuration structure remains the same. I don't have any examples right now, but basically in your startup somewhere you would just make sure the Saml2Config is initiated from a Saml2ConfigBuilder, as otherwise on first access it will try and initiate from the config file instead.

Something like this:

    var builder = new SAML2.Config.Builder.Saml2ConfigBuilder();
    builder.AddAction(new SAML2.Config.Action { Name = "ActionName", Type = "ActionType" });
    builder.AddAllowedAudienceUri("AllowedUri");
    builder.WithAssertionValidator("AssertionValidator");

    var config = builder.Build();
    SAML2.Config.Saml2Config.Init(config);

You'll have to explore the builder a bit, but pretty much everything in the docs here for a config is represented there.
