### ISSUE TITLE
SignsXml Test Fails

### ISSUE THREAD

**Issue by dougwebb** [i8beef/SAML2#51]
The app.config specifies CN=ServiceProvider as the signing certificate, but the Certificates folder doesn't provide that cert. It would be handy if there was a cert to just install rather than having to create it. But at minimum the test should document the parameters needed to create the cert.

**Comment by i8beef** [comment]
That test is marked as Explicit on purpose, as this method is meant for manual testing of the signing mechanism for any cert you want. It's not meant for general consumption.
