### ISSUE TITLE
SigningCertificate is mandatory ?

### ISSUE THREAD

**Issue by muadhib** [i8beef/SAML2#52]
Hi,  
I'm testing SAML 2 package to add SAML 2 protocole on our website.  
When I'm goint at https://localhost:12345/login.ashx, I have a Null Reference Exception. In my debug console, it's seems it's caused by Saml20SignonHandler:44 (Saml2Config.Current.ServiceProvider.SigningCertificate is Null).  
When we consult the wiki (https://github.com/i8beef/SAML2/wiki/Configuration-Examples), signingCertificate is not mark as mandatory.  

It's my saml's part :
```
  <saml2>
    <allowedAudienceUris>
      <audience uri="test" />
    </allowedAudienceUris>
    <serviceProvider id="test" server="https://localhost:44315/">
      <endpoints>
        <endpoint localPath="Login.ashx" type="SignOn" redirectUrl="~/AuthenticatedHomePage" />
        <endpoint localPath="Logout.ashx" type="Logout" redirectUrl="~/HomePage" />
        <endpoint localPath="Metadata.ashx" type="Metadata" />
      </endpoints>
    </serviceProvider>
    <identityProviders metadata="C:\Users\CNN\source\repos\SAML2Bomberman\src\WebApplication1\IDP"/>
  </saml2>

```

Where i'm wrong ?

Thanks !

**Comment by i8beef** [comment]
Yes, SAML requires a signing certificate to avoid MitM modification of responses.
