### ISSUE TITLE
CacheStateService uses old cookies instead of the current request

### ISSUE THREAD

**Issue by mvian** [i8beef/SAML2#57]
CacheStateService stores a reference to HttpContext passed in during initialization. Because CacheStateService is initialized only once, the same HttpContext is referenced in all further calls to the state service. The HttpContext "encapsulates all HTTP-specific information about **an individual HTTP request**", so the Request and Response properties continue to represent the request and response of the **initial** request that triggered CacheStateService initialization.

When GetCacheKeyPrefix is called, it uses the context.Request.Cookies to check for an existing SAML2Session cookie, and if not found, sets a new one using context.Response. I imagine that the intent was to look at the individual user's cookies to give a unique cache prefix, to handle multiple users logging in at the same time. Because the HttpContext in use is held over from instantiation, the cookies read are always the cookies from the initial request, the cookie values do not vary by request/user, and only one cache prefix is ever generated.

In practice we have seen this result in errors when multiple users sign in at the same time - they are likely to encounter a Saml20Exception of either "Session ExpectedInResponseTo missing" or "Possible replay attack detected, unexpected value".

**Comment by i8beef** [comment]
That does seem like a rather glaring issue. That state service wasn't original here, but we found when the Content Security Policy default changes that occurred earlier this year went live in the browsers, that this implementation ended up being better than the session storage approach... in updating it for that case, I think I missed the fact that the original implementation did this, it was just fine until cookies entered the mix.

I am pushing another branch, but sadly I don't actually have a way to test anymore... if you get a chance to test out this PR and see if you think it addresses your concern? If you can actually try it that would be great.

https://github.com/i8beef/SAML2/pull/58

**Comment by mvian** [comment]
I've tested with the 57-HttpContextFix branch. The changes in that branch make sense to me and everything looked good in my testing. A new CacheKeyPrefix and SAML2Session cookie is generated when (and only when) the user doesn't already have a SAML2Session cookie, and multiple logins can be processed at the same time.

Thank you! We look forward to a NuGet release with these changes :)

**Comment by i8beef** [comment]
I am pushing a release for this now as this seems rather serious. New version should be available momentarily.

**Comment by i8beef** [comment]
Closed as complete
