### ISSUE TITLE
Certificate not found error on Windows Container

### ISSUE THREAD

**Issue by nreddipalle** [i8beef/SAML2#60]
@i8beef SAML2 showing certificate not found error on Windows IIS Container.
Cert is added to CurrentUser My location and the signing certificate under SAML.config shows as 
<signingCertificate findValue="CC4376BC1C2890D56FF8420192296C53" storeLocation="CurrentUser" storeName="My" x509FindType="FindByThumbprint" />

But still the app is displaying Certificate not found Error

FYI. The same works fine using Azure App Service.

Thanks

**Comment by i8beef** [comment]
As in Docker container? Im afraid I can't be of much help there if that's the case, but you'd have to figure out how to allow the container to access the cert store of the host, or how to stand up a cert store WITHIN the container (not sure how possible that is).

**Comment by nreddipalle** [comment]
@i8beef I am able to figure out the certificate not found error but now seeing a different one.. any idea about this?
![image](https://user-images.githubusercontent.com/28302399/98254105-e03b7a00-1f49-11eb-941d-8edd04c7beb1.png)

**Comment by i8beef** [comment]
Could be a permissions issue. In a Windows cert store, you have to give the user running the app access to the private key of the cert in question.

From the wiki:

It is important to note that the application must have access to the private key of the certificate in the key store. This can be done from mmc.exe and the Certificates snap-in. The private key permissions must be set to allow Read permissions for the identity the App Pool is running under. On IIS7+, this could be the IIS_IUSRS group if you are not running the App Pool under a different identity.

**Comment by nreddipalle** [comment]
This is working now. Closing the issue.
