### ISSUE TITLE
configuration issue

### ISSUE THREAD

**Issue by thisisata** [i8beef/SAML2#61]
while calling the signon handler (/Login.ashx), the following error message is displyed. Any Clues in case if i am missing something. Thanks in advance for your efforts and time.
[
![SSOError](https://user-images.githubusercontent.com/5272017/100075146-04a7b980-2e59-11eb-8c3e-363e41fd8f6c.png)
](url)

**Comment by i8beef** [comment]
Given your other issue, Im guessing this is probably failure to specify the config values for signing certificates.

**Comment by thisisata** [comment]
**Can this library create the unsigned authentication request through signon handler?**
Is it necessary to specify signing certificates? Is there any attribute for "ServiceProvider" element to send request without signing, like "omitAssertionSignatureCheck" is there for "IdentityProvider" element.

Thanks for ur support.

**Comment by i8beef** [comment]
Yes, you have to use a signing certificate.

**Comment by thisisata** [comment]
Thanks for ur timely reply, now I will create the certificate and use it as per the instructions. But this is just for signing and if **identity provider**, like in my case, does not want to use the certificate, so still identity provider will be able to parse my signon request.

**Comment by thisisata** [comment]
And this certificate is to just signing the request **and not for encryption.**
