### ISSUE TITLE
Is it allowed to create the authentication request without signing with certificate?

### ISSUE THREAD

**Issue by thisisata** [i8beef/SAML2#62]
I  don't want to use the certificates at SP level and and its agreed that Identity Provider will also not use any certificates and the assertions sent back to SP will not be signed. For identity provider section i  can use "omitAssertionSignatureCheck" attribute but for the ServiceProvider Element, is there any specific attribute if i don't want to use certificates for SP.

Thanks in advance for ur precious support and help.

**Comment by i8beef** [comment]
Sorry, not supported as an insecure configuration.
