### ISSUE TITLE
saml2.exception.saml20Exception

### ISSUE THREAD

**Issue by thisisata** [i8beef/SAML2#67]
Hi, Sorry to bother you again,
Now got stuck with this exception, after the reponse received from Idp.
saml2.exception.saml20Exception with status code **saml2.schema.Protocol.Status** received when **Success** was expected.

Thanks in Advance

**Comment by i8beef** [comment]
The log message is actually messed up here. I actually fixed this earlier in the month but didn't push it. I just did so it will log the correct error. Whatever your issue is here, though, your IDP is rejecting one of your requests, so something isn't right with your config.

**Comment by i8beef** [comment]
Closing as the new log message should make this clearer, and you seem to have already gotten past this part.
