### ISSUE TITLE
using SAML2.Logging.Log4Net with latest version

### ISSUE THREAD

**Issue by thisisata** [i8beef/SAML2#70]
Can I use SAML2.Logging.Log4Net with latest version of saml2.
And where does this logging happens, I mean where Can I see the logs.

**Comment by i8beef** [comment]
Nothing's really changed that I know of in that regard. Try it, and if it is broken report it. The only things Im aware of changing with log4net is some issues around their signing cert changes a few years ago, but no one's reported any issues.

Where it spits logs is up to your log4net configuration for your app.

**Comment by thisisata** [comment]
When added the nuget package for log4net[SAML2.Logging.Log4Net 2.3.1] then it automatically included the old version[SAML 2.3.1] of 2013. That anyway I manually updated again with new version.
Related to log4net configuration in my app, its just this line i added in saml2 section of my config [logging loggingFactory="SAML2.Logging.Log4Net.Log4NetLoggerFactory, SAML2.Logging.Log4Net" ]. 
But where it will write the logs, I mean the default location.

**Comment by hardikcc** [comment]
Could you figure out where are the logs written?

**Comment by i8beef** [comment]
The log location is dependent on your Log4Net configuration. This library only makes the SAML library hook its logging into an EXISTING log4net setup, it doesn't add any default logging configuration.

**Comment by i8beef** [comment]
Closing as stale
