### ISSUE TITLE
Unable to logout.

### ISSUE THREAD

**Issue by ghost** [i8beef/SAML2#72]
I am unable to logout. It throws error "Unknown identity provider". Login works fine. Screenshot attached.

![image](https://user-images.githubusercontent.com/12234501/114307896-36b17380-9afb-11eb-9308-532f6c74c99e.png)

**Comment by i8beef** [comment]
If you are using SingleLogOut (SLO) the IDP has to issue you a SessionIndex in the AuthStatement. Are you trying to do actual SLO (then likely a IDP setup issue here), or are you just trying to log a user out of your application? Because those are two different things. One is killing a shared login session on the IDP, and one is killing the authenticated session in your application state.

**Comment by ghost** [comment]
Below is the detail.

1- First i tried to logout of the application using FormsAuthentication.SignOut(). But after calling this function Login.ashx doesn't show up with the sso login page, it actually login user again. Actually above SignOut function doesn't work. I also tried expiring cookies, screenshot attached, but this also doesn't work. If this step works it would be easiest.

![image](https://user-images.githubusercontent.com/12234501/114353954-0dd6c000-9b87-11eb-91d5-524e73e7d5f6.png)

2- So in the next step i tried actual SLO. By calling logout.ashx. WebConfig and ipd meta attached.

SAML2 webconfig section:

![image](https://user-images.githubusercontent.com/12234501/114353287-4924bf00-9b86-11eb-9b51-e275b52b1ebc.png)

IDP Meta:

![image](https://user-images.githubusercontent.com/12234501/114353692-bf292600-9b86-11eb-8f8a-4b03e73eb15e.png)


Right now i have to close the browser to log user out.

**Comment by i8beef** [comment]
I don't think you are doing what you think you are. Your IDP metadata does not show support for SLO, so either you need to set that up, or you need to do something different.

I suspect what you actually had is your logout page was redirecting after it was done to a page that requires auth, which just starts the auth handshake over again, and your IDP has a session that is still active. So when it redirects to them, it doesn't have to login again, it just uses the identity still in its session and immediately returns the SAML response for that identity.

SLO is built to do what you appear to want, if they supported it, but allowing ANY SP to trigger a logout of the identity for ALL SPs for that user isn't always what they want to allow. In which case, the best you can do is your logout logs them out of your app, and then redirects them to a public (non-authed) page that says "You've been logged out of app X".

**Comment by i8beef** [comment]
Closing as stale
