### ISSUE TITLE
Unable to login when published on iis

### ISSUE THREAD

**Issue by ghost** [i8beef/SAML2#73]
I am facing an issue on login using saml. The site is published on iis. This screenshot has been taken from aws ec2 instance (windows server). Here it stucks around 30 seconds on SAMLRequest then this error came.

![ReleaseRequestState](https://user-images.githubusercontent.com/12234501/114398743-92423680-9bb9-11eb-917c-102a7fba3f50.png)

On my local machine windows 10 iis i reproduced this error twice. But now its working fine.

**Comment by i8beef** [comment]
Im afraid that doesn't give much to work with without an error log of some sort.

**Comment by ghost** [comment]
i will try to debug on ec2 instance and will share you where its crashing

**Comment by ghost** [comment]
Closing this one. was some configuration issue
