### ISSUE TITLE
Error generating metadata

### ISSUE THREAD

**Issue by shnal** [i8beef/SAML2#74]
Hi, 

I am interested in using this package to consume an incoming SAML assertion.

I have configured my project taking instruction from the Wiki.

I am running the project up and navigating to /metadata.ashx

I expect to the see the metadata XML. I get an error.

![image](https://user-images.githubusercontent.com/12751143/182404711-9b57b707-cf09-4ced-a4c2-3bd6c4bdb6e6.png)

My saml2 config section:

("myapp" used in place of actual app name).

	<saml2>
		<allowedAudienceUris>
			<audience uri="http://www.example.com" />
		</allowedAudienceUris>
		<serviceProvider id="urn:SPName" server="https://staging.myapp.co.uk">
			<endpoints>
				<endpoint localPath="Login.ashx" type="SignOn" redirectUrl="~/AuthenticatedHomePage" />
				<endpoint localPath="Logout.ashx" type="Logout" redirectUrl="~/HomePage" />
				<endpoint localPath="Metadata.ashx" type="Metadata" />
			</endpoints>
			<nameIdFormats allowCreate="true">
				<add format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"/>
			</nameIdFormats>
			<authenticationContexts comparison="Exact">
				<add context="urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport" referenceType="AuthnContextClassRef"/>
			</authenticationContexts>
		</serviceProvider>
		<identityProviders metadata="c:\temp\metadata">
			<add id="idpext-qc.aon.com"/>
		</identityProviders>
		<actions>
			<clear/>
			<action name="SetSamlPrincipal" type="SAML2.Actions.SamlPrincipalAction, SAML2" />
			<action name="AuthenticationAction" type="myapp.CustomSamlActions.AuthenticationAction, myapp" />
			<action name="Redirect" type="SAML2.Actions.RedirectAction, SAML2" />
		</actions>
	</saml2>

Any pointers as to what I am doing wrong would be much appreciated

**Comment by i8beef** [comment]
I believe you are missing the `signingCetificate` element in your config:

https://github.com/i8beef/SAML2/wiki/ServiceProvider-Element

**Comment by shnal** [comment]
Thanks @i8beef ,

You are correct.

I have added this and also needed to generate a certificate in a windows 10 environment. MakeCert is deprecated now and I also had little luck using Powershell. 

OpenSSL (included with git for windows) seems to be the one that worked for me using two commands:

1. To generate a .crt with separate .key file:
`openssl.exe req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout privateKey.key -out certificate.crt`

2. To be able to import into windows certificate store along with the key, use of openssl to combine the above files and produce a single .pfx file.

`openssl pkcs12 -export -out cert.pfx -inkey privateKey.key -in certificate.crt -certfile certificate.crt`
