### ISSUE TITLE
Suitability for IDP Initiated SSO

### ISSUE THREAD

**Issue by shnal** [i8beef/SAML2#75]
I have a .NET 4.5 web application which I would like to use SAML2 with.

In our SSO scenario we are a service provider. 

An external application exists with an external identity provider.

The external identity provider plans to send a SAML assertion to our application. We will need to consume the SAML assertion and take custom actions to authenticate and authorise the user specified in the SAML assertion.

Does this approach make sense and will SAML2 be suitable in this scenario?

I note that we are not initiating the login from our SP application, we only need to consume SAML assertions from the external IDP.

**Comment by shnal** [comment]
To add a little further information. 

I have tried a POST HTTP request using postman to /login.ashx. The body of the request is a XML formatted SAML assertion.

I am expecting that the SAML is processed and to be able to hit a breakpoint within my custom authentication Handler.

I get  HTTP 200 back in Postman, but with HTML markup and the "Choose Identity Provider" message.

![image](https://user-images.githubusercontent.com/12751143/182566622-5dcf0d1f-af08-44e8-b6a7-8828ea141760.png)

![image](https://user-images.githubusercontent.com/12751143/182567233-978956bf-893a-475f-a031-c9e679696342.png)


Perhaps this is caused by my <IdentityProviders> .. </IdentityProviders> section within my config and/or the content of the SAML payload itself?

**Comment by i8beef** [comment]
This library isn't really built to do generic SAML processing, its a complete implementation for handling the flow end to end. So no, I don't think you could just use exposed public class within it to generically process arbitrary SAML assertions. An IDP initiated flow is possible with SAML, but I have never done it...

I believe they need to send it as a base-64 encoded query string param named "SamlResponse" with the assertion: https://github.com/i8beef/SAML2/blob/master/src/SAML2/Protocol/Saml20SignonHandler.cs#L158

That is, they need to "act like" a SAML response from a normal flow, but you kinda have to turn off some security checks to allow "unsolicited" responses. I think your configuration needs to specify the AllowUnsolicitedResponses option to skip replay attack checks.

See the allowUnsolicitedResponses setting for your IDP config. 
https://github.com/i8beef/SAML2/wiki/IdentityProviders-Element

The rest I THINK just plays out like normal after that point. You can basically walk through that linked class to see the signon process from the Handle method... I can try and answer questions, but I haven't really used SAML now in several years now, so Im a little rusty on usage, especially on areas of the library I've never touched.

https://github.com/i8beef/SAML2/blob/master/src/SAML2/Protocol/Saml20SignonHandler.cs

**Comment by shnal** [comment]
Thanks @i8beef,

That helps and makes sense. 

I think I need to have another look around to see if there's something readily available. Otherwise I may return to SAML2.

Thanks for your response and for clarifying.

**Comment by i8beef** [comment]
Understood. Let me know if you need more help!
